# Generated by Django 2.2.9 on 2021-08-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210810_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group',
        ),
    ]
